version: "{build}"
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true

cache: ..\openclonk-cache

configuration: RelWithDebInfo
platform:
  - Win32
  - x64

install:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER\\tools\\ci\\appv-Install.ps1"
before_build:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER\\tools\\ci\\appv-BeforeBuild.ps1"
build:
  project: ../openclonk-build/openclonk.sln
  verbosity: minimal
after_build:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER\\tools\\ci\\appv-AfterBuild.ps1"
test_script:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER\\tools\\ci\\appv-Test.ps1"

deploy: off
